name: Go CI

on:
  push:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Go Fmt
        run: go fmt ./...

      - name: Go Vet
        run: go vet ./...

      - name: Go Test
        run: go test ./...
